modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/acorsicanfrog/animalgenders/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/acorsicanfrog/animalgenders/main/updates.json"
displayURL="https://modrinth.com/mod/animal-genders"
logoFile="assets/${mod_id}/logo.png"
authors="A Corsican Frog"
description='''
Adds Gender to All Minecraft Animals

Introduces male and female genders for all animals.

Breeding now respects gender: only male + female pairings are possible.

Female animals have exclusive abilities:
- Laying eggs (chickens)
- Being milked (cows)

Designed to be compatible with most animal mods. If you encounter issues, I'll work to fix them!
'''

[[mixins]]
config="mixins.animalgenders-common.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"